# Generated by Django 5.0.6 on 2024-05-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cap',
            name='images',
        ),
        migrations.AddField(
            model_name='cap',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
